-- --laundryAShop_schema.sql
-- --TRUNCATE TABLE LAUNDRY_SHOP;


-- DROP TABLE IF EXISTS LAUNDRY_SHOP_SERVICES;

-- DROP TABLE IF EXISTS LAUNDRY_SHOP_PRODUCTS;

-- DROP TABLE IF EXISTS LAUNDRY_SHOP_WORKING_DAYS_AND_TIME;

-- DROP TABLE IF EXISTS PRODUCT;

-- DROP TABLE IF EXISTS SERVICESWASH;

-- DROP TABLE IF EXISTS WORKING_DAYS_AND_TIME;

-- DROP TABLE IF EXISTS LAUNDRY_SHOP;

-- DROP TABLE IF EXISTS OFFERS_AND_COUPONS;

-- CREATE TABLE LAUNDRY_SHOP (
--     SHOP_ID INTEGER PRIMARY KEY,
--     NAME VARCHAR(255),
--     ADDRESS VARCHAR(255)
--  --  WORKING_DAYS_AND_TIME DATE
--  -- Add other columns as needed
-- );

-- CREATE TABLE SERVICESWASH (
--     SERVICE_ID INTEGER PRIMARY KEY,
--     SERVICE_NAME VARCHAR2 (50),
--     ICON_NAME VARCHAR2 (50)
-- );

-- CREATE TABLE PRODUCT (
--     PRODUCT_ID INTEGER PRIMARY KEY,
--     PRODUCT_NAME VARCHAR(255),
--     QUANTITY INTEGER,
--     PRICE DOUBLE,
--     ORIGINALPRICE DOUBLE,
--     IMAGE_PATH VARCHAR2 (255)
-- );

-- CREATE TABLE WORKING_DAYS_AND_TIME(
--     WORKING_ID INTEGER PRIMARY KEY,
--     DAYS VARCHAR(255),
--     OPEN_TIME TIME,
--     CLOSE_TIME TIME,
--     SHOP_ID INTEGER REFERENCES LAUNDRY_SHOP(SHOP_ID)
-- );

-- CREATE TABLE LAUNDRY_SHOP_SERVICES (
--     SHOP_ID INTEGER REFERENCES LAUNDRY_SHOP (SHOP_ID),
--     SERVICE_ID INTEGER REFERENCES SERVICESWASH (SERVICE_ID),
--     PRIMARY KEY (SHOP_ID, SERVICE_ID)
-- );

-- -- Create the table for LaundryShopProducts relationship
-- CREATE TABLE LAUNDRY_SHOP_PRODUCTS (
--     SHOP_ID INTEGER REFERENCES LAUNDRY_SHOP (SHOP_ID),
--     PRODUCT_ID INTEGER REFERENCES PRODUCT (PRODUCT_ID),
--     PRIMARY KEY (SHOP_ID, PRODUCT_ID)
-- );

-- -- TABLE FOR OFFERS AND COUPONS
-- CREATE TABLE OFFERS_AND_COUPONS(
--     OFFER_ID INTEGER PRIMARY KEY,
--     OFFERS VARCHAR(255),
--     COUPON_CODE VARCHAR(100),
--     PAYMENT_MODE VARCHAR(100)
-- )

-- Table for LaundryShop with AUTO_INCREMENT on shop_id
CREATE TABLE IF NOT EXISTS laundry_shop (
    shop_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    address VARCHAR(255)
);

-- Table for ServicesWash with AUTO_INCREMENT on service_id
CREATE TABLE IF NOT EXISTS services_wash (
    service_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    service_name VARCHAR(100),
    icon_name VARCHAR(100)
);

-- Join table for LaundryShop and ServicesWash
CREATE TABLE IF NOT EXISTS laundry_shop_services (
    shop_id INTEGER,
    name VARCHAR(255),
    address VARCHAR(255),
    service_name VARCHAR(100),
    PRIMARY KEY (shop_id),
    FOREIGN KEY (shop_id) REFERENCES laundry_shop(shop_id) ON DELETE CASCADE,
    FOREIGN KEY (name) REFERENCES laundry_shop(name) ON DELETE CASCADE,
    FOREIGN KEY (address) REFERENCES laundry_shop(address) ON DELETE CASCADE,
    FOREIGN KEY (service_name) REFERENCES services_wash(service_name) ON DELETE CASCADE 
);

-- CREATE TABLE IF NOT EXISTS laundry_shop_service_summary (
--     shop_id BIGINT PRIMARY KEY,
--     shop_name VARCHAR(255) NOT NULL,
--     shop_address VARCHAR(255) NOT NULL,
--     services_list VARCHAR(1000)  -- To store comma-separated services
-- );
