INSERT INTO SERVICESWASH(ID,SERVICE_NAME,ICON_NAME) VALUES (1,'WASH','wash');
INSERT INTO SERVICESWASH(ID,SERVICE_NAME,ICON_NAME) VALUES (2,'WASH AND IRON','washAndIron');
INSERT INTO SERVICESWASH(ID,SERVICE_NAME,ICON_NAME) VALUES (3,'DRY CLEAN','dry clean');